services:
  app:
    image: credit-card-reader:latest
    container_name: credit_card_reader_app
    environment:
      API_PORT: 8081
      API_BASE_PATH: credit-card-reader
      DB_URI: mongodb://credit_card_reader_mongo:27017
      DB_NAME: credit-card-bill-transactions
    ports:
      - "8081:8081"
    depends_on:
      - credit_card_reader_mongo

  credit_card_reader_mongo:
    container_name: credit_card_reader_mongo
    image: bitnami/mongodb:6.0
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=credit-card-bill-transactions
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=pass
    volumes:
      - credit_card_reader_mongo_data:/bitnami/mongodb

volumes:
  credit_card_reader_mongo_data:
