# run
run-uploader:
	python3 src/main.py

# config
install:
	pip3 install -r requirements.txt

freeze:
	pip3 freeze > requirements.txt

# venv
create-venv:
	python3 -m venv venv-credit-card-uploader

activate:
	source venv-credit-card-uploader/bin/activate

exit-venv:
	deactivate
